[package]
name = "exrs"
version = "0.1.0"
authors = ["zp <zhenpingfeng@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
chrono = "0.4.19"
csv = "1.1.6"
env_logger = "0.8.4"
error-chain = { version = "0.12.4", default-features = false }
hashbrown = { version = "0.11.2", features = ["serde"] }
hex = "0.4.3"
hmac = "0.11.0"
log = "0.4.14"
reqwest = { version = "0.11.4", features = ["json", "blocking", "rustls-tls"] }
rust_decimal = { version = "1.14.3", features = ["maths", "serde-arbitrary-precision"] }
rust_decimal_macros = "1.14"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.9.5"
tokio = { version = "1.7.1", features = ["full"] }
tokio-tungstenite = { version = "0.14.0", features = ["rustls-tls"] }
tungstenite = { version = "0.13.0", features = ["rustls-tls"] }
url = "2.2.2"
